#pragma config(Sensor, dgtl6,  Touch,          sensorTouch)
#pragma config(Motor,  port3,           FrontL,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port2,           FrontR,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           BackL,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           BackR,         tmotorServoContinuousRotation, openLoop)

#pragma config(Motor,  port6,           FrontL,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           FrontR,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           BackL,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           BackR,         tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
 bool toggle = false;
 	int vert;
	int hori;

 while(true) {

  if(SensorValue(Touch)){
  	while(SensorValue(Touch)){
  	}
  	//waitUntil(!SensorValue(Touch));

  	toggle = !toggle;
  }


	if(toggle){
	   	motor[FrontL] = -127;
	   	motor[FrontR] = 127;
	   	motor[BackL] = 127;
	 		motor[BackR]  = -127;
		}
	else{
			motor[FrontL] = 0;
	   	motor[FrontR] = 0;
	   	motor[BackL] = 0;
	 		motor[BackR]  = 0;
	 		}

	 	vert = vexRT[Ch3];
		hori = vexRT[Ch4];


		if(vert > -10 && vert < 10)
			vert = 0;

		if(hori > -10 && hori < 10)
			hori = 0;

			motor[FrontL]= hori + vert;
			motor[BackL]= hori + vert;
			motor[FrontR]= hori - vert;
			motor[BackR]= hori - vert;
	}


}
